/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package paineis;

import classes.ImprimirZebra;
import java.awt.event.KeyEvent;
import javax.print.PrintException;
import javax.swing.JOptionPane;

/**
 *
 * @author lucas.vieira
 */
public class EtqArmazenagem extends javax.swing.JPanel {

    ImprimirZebra impressao = new ImprimirZebra();
    String rua = "";
    String pos = "";
    String excesso = "";

    /**
     * Creates new form EtqArmazenagem
     */
    public EtqArmazenagem() {
        initComponents();

        zeraCampos();
    }

    public void zeraCampos() {
        setaFoco();
        ruaTxt.setText("");
        posIniTxt.setText("");
        rua = "";
        String pos = "";
        excesso = "";
        
    }
    
    public void setaFoco() {
        ruaTxt.requestFocus();
    }

    public void processamento() {
        rua = ruaTxt.getText();
        pos = posIniTxt.getText();
        if (rua.length() < 1 || rua.length() > 2 || pos.length() != 3) {
            JOptionPane.showMessageDialog(null, "Dados Inválidos");
        } else {

            if (rua.length() == 1) {
                rua = "0" + rua;
            }
            pos = pos.toUpperCase();
            
            excesso = "R" + rua + pos;

            imprimir();
            zeraCampos();
        }
    }
    
    
    public void imprimir() {
        impressao.imprime("^XA~TA000~JSN^LT0^MNW^MTD^PON^PMN^LH0,0^JMA^PR4,4~SD15^JUS^LRN^CI0^XZ\n"
                + "^XA\n"
                + "^MMT\n"
                + "^PW695\n"
                + "^LL0855\n"
                + "^LS0\n"
                + "^FO21,18^GB666,824,8^FS\n"
                + "^FT164,623^A0N,127,124^FH\\^FDRUA "+rua+"^FS\n"
                + "^BY3,3,85^FT203,752^BCN,,Y,N\n"
                + "^FD>:"+excesso+"^FS\n"
                + "^FT87,370^A0N,352,348^FH\\^FD"+pos+"^FS\n"
                + "^LRY^FO30,27^GB649,0,453^FS^LRN\n"
                + "^PQ1,0,1,Y^XZ");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Fixo = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ruaTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        posIniTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(50, 76, 156));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Impressão de etiqueta de Excesso");

        jLabel1.setText("Rua :");

        ruaTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Posição :");

        posIniTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        posIniTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posIniTxtActionPerformed(evt);
            }
        });

        jButton1.setText("Imprimir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButton1KeyPressed(evt);
            }
        });

        javax.swing.GroupLayout FixoLayout = new javax.swing.GroupLayout(Fixo);
        Fixo.setLayout(FixoLayout);
        FixoLayout.setHorizontalGroup(
            FixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FixoLayout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(FixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addGroup(FixoLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(FixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(FixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(FixoLayout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(posIniTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(FixoLayout.createSequentialGroup()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(48, 48, 48)
                                    .addComponent(ruaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(194, Short.MAX_VALUE))
        );
        FixoLayout.setVerticalGroup(
            FixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FixoLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel28)
                .addGap(49, 49, 49)
                .addGroup(FixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ruaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(FixoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(posIniTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fixo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Fixo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Fixo.getAccessibleContext().setAccessibleName("etqexcesso");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButton1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            processamento();
        }
    }//GEN-LAST:event_jButton1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        processamento();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void posIniTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posIniTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_posIniTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fixo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JTextField posIniTxt;
    private javax.swing.JTextField ruaTxt;
    // End of variables declaration//GEN-END:variables
}
